(function(){
  const caseId = 'PW-' + Date.now().toString(36).toUpperCase();
  document.getElementById('caseId').textContent = 'CASE REF: ' + caseId;

  const analyzeBtn = document.getElementById('analyzeBtn');
  const resetBtn = document.getElementById('resetBtn');
  const downloadBtn = document.getElementById('downloadBtn');
  const readout = document.getElementById('riskReadout');

  let lastReport = null;

  function reportToText(r){
    return `FAKE PROFILE COMPLAINT REPORT
==============================
Case reference: ${r.caseId}
Generated: ${r.generatedAt}

PLATFORM: ${r.platform}
PROFILE: ${r.profileUrl}
IMPERSONATING: ${r.impersonating}

DESCRIPTION OF ISSUE:
${r.description}

RISK ASSESSMENT
----------------
Score: ${r.score} / 100
Level: ${r.level}

RED FLAGS OBSERVED:
${r.signals.length ? r.signals.map(s => '- ' + s).join('\n') : '- None selected'}

REPORTER CONTACT (for your own records): ${r.reporterContact || 'Not provided'}

------------------------------
Generated by Profile Watch — for submission to your local cybercrime cell
(e.g. cybercrime.gov.in) or the platform's official report tool.
This is a citizen-prepared report and does not constitute an official
police record on its own.
`;
  }

  analyzeBtn.addEventListener('click', () => {
    const platform = document.getElementById('platform').value;
    const profileUrl = document.getElementById('profileUrl').value.trim();
    const impersonating = document.getElementById('impersonating').value.trim();
    const description = document.getElementById('description').value.trim();
    const reporterContact = document.getElementById('reporterContact').value.trim();

    if(!profileUrl || !impersonating || !description){
      alert('Please fill in the required fields: profile URL/username, who it impersonates, and a description.');
      return;
    }

    const checked = Array.from(document.querySelectorAll('.flag:checked'));
    let score = checked.reduce((sum, el) => sum + Number(el.dataset.weight), 0);
    score = Math.min(score, 100);

    let level, levelClass;
    if(score >= 55){ level = 'High risk'; levelClass = 'risk-high'; }
    else if(score >= 25){ level = 'Medium risk'; levelClass = 'risk-med'; }
    else { level = 'Low risk'; levelClass = 'risk-low'; }

    document.getElementById('riskScore').textContent = score;
    const labelEl = document.getElementById('riskLabel');
    labelEl.textContent = level;
    labelEl.className = 'risk-label ' + levelClass;

    document.getElementById('riskSummary').textContent = checked.length
      ? `Based on ${checked.length} flagged signal(s), this profile shows characteristics consistent with impersonation/scam activity.`
      : 'No specific red flags were ticked — score reflects the description alone. Consider reviewing the checklist again if you noticed any of these signs.';

    const list = document.getElementById('signalList');
    list.innerHTML = '';
    if(checked.length === 0){
      const li = document.createElement('li');
      li.textContent = 'No checklist signals selected.';
      list.appendChild(li);
    } else {
      checked.forEach(el => {
        const li = document.createElement('li');
        li.textContent = '• ' + el.dataset.label;
        list.appendChild(li);
      });
    }

    readout.classList.add('show');

    lastReport = {
      caseId, platform, profileUrl, impersonating, description,
      reporterContact, score, level,
      signals: checked.map(el => el.dataset.label),
      generatedAt: new Date().toLocaleString()
    };
  });

  resetBtn.addEventListener('click', () => {
    document.querySelectorAll('input[type=text], textarea').forEach(el => el.value = '');
    document.querySelectorAll('.flag').forEach(el => el.checked = false);
    document.getElementById('platform').selectedIndex = 0;
    readout.classList.remove('show');
    lastReport = null;
  });

  downloadBtn.addEventListener('click', () => {
    if(!lastReport){ alert('Run "Analyze report" first.'); return; }
    const blob = new Blob([reportToText(lastReport)], {type: 'text/plain'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `complaint-report-${lastReport.caseId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });

  // ---- Case list (multi-profile tracking) ----
  const STORAGE_KEY = 'profileWatchCases';
  const caseListPanel = document.getElementById('caseListPanel');
  const caseTableBody = document.getElementById('caseTableBody');
  const saveCaseBtn = document.getElementById('saveCaseBtn');
  const downloadAllBtn = document.getElementById('downloadAllBtn');
  const clearCasesBtn = document.getElementById('clearCasesBtn');

  function loadCases(){
    try{ return JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; }
    catch(e){ return []; }
  }
  function saveCases(cases){
    localStorage.setItem(STORAGE_KEY, JSON.stringify(cases));
  }
  function renderCases(){
    const cases = loadCases();
    caseTableBody.innerHTML = '';
    caseListPanel.style.display = cases.length ? 'block' : 'none';
    cases.forEach((c, idx) => {
      const tr = document.createElement('tr');

      const tdCase = document.createElement('td');
      tdCase.style.fontFamily = 'var(--mono)';
      tdCase.textContent = c.caseId;

      const tdPlatform = document.createElement('td');
      tdPlatform.textContent = c.platform;

      const tdProfile = document.createElement('td');
      tdProfile.style.cssText = 'max-width:180px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;';
      tdProfile.textContent = c.profileUrl;
      tdProfile.title = c.profileUrl;

      const tdRisk = document.createElement('td');
      tdRisk.textContent = `${c.score} (${c.level})`;

      const tdSaved = document.createElement('td');
      tdSaved.style.cssText = 'font-family:var(--mono); font-size:11px;';
      tdSaved.textContent = c.generatedAt;

      const tdRemove = document.createElement('td');
      const removeBtn = document.createElement('button');
      removeBtn.type = 'button';
      removeBtn.className = 'secondary';
      removeBtn.style.cssText = 'padding:4px 10px; font-size:11px;';
      removeBtn.textContent = 'Remove';
      removeBtn.addEventListener('click', () => {
        const current = loadCases();
        current.splice(idx, 1);
        saveCases(current);
        renderCases();
      });
      tdRemove.appendChild(removeBtn);

      tr.append(tdCase, tdPlatform, tdProfile, tdRisk, tdSaved, tdRemove);
      caseTableBody.appendChild(tr);
    });
  }

  saveCaseBtn.addEventListener('click', () => {
    if(!lastReport){ alert('Run "Analyze report" first.'); return; }
    const cases = loadCases();
    cases.push(lastReport);
    saveCases(cases);
    renderCases();
  });

  downloadAllBtn.addEventListener('click', () => {
    const cases = loadCases();
    if(!cases.length){ alert('No saved cases yet.'); return; }
    const text = cases.map(reportToText).join('\n\n========================================\n\n');
    const blob = new Blob([text], {type: 'text/plain'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `profile-watch-all-cases-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });

  clearCasesBtn.addEventListener('click', () => {
    if(confirm('Remove all saved cases from this browser?')){
      localStorage.removeItem(STORAGE_KEY);
      renderCases();
    }
  });

  renderCases();
})();
